### ISSUE TITLE
How to flush dns cache?

### ISSUE THREAD

**Issue by Huddeij** [mpgirro/docker-pihole-unbound#275]
I am using a one container solution as a dns resolver. Everytime, when the external IP get's reset, I add the new ip in my provider's dns entries per script. This takes about 5 minutes until the external services are reset. And I can reach out to them from my local client pc when I use a vpn. But I have to wait the whole day until I can reach the public services.
A quick dig command reveals, that the dns used by the pihole is still the old one from before the ip refresh.

compose.yaml:
```
services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    network_mode: "host"  # Use host networking instead
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: <redacted>
      WEBTHEME: "lcars"
      DNSMASQ_LISTENING: all
      FTLCONF_LOCAL_IPV4: "192.168.0.42"
      DNS1: "127.0.0.1#5335"
      DNS2: "8.8.8.8"
      WEB_PORT: "81"
      REV_SERVER: "true"
      REV_SERVER_TARGET: "192.168.0.1"
      REV_SERVER_DOMAIN: "huddeij.de"
      REV_SERVER_CIDR: "192.168.0.0/24"
      DNSSEC: "true"
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    volumes:
      - './etc_pihole-unbound:/etc/pihole'
      - './etc_pihole_dnsmasq-unbound.d:/etc/dnsmasq.d'
    restart: unless-stopped
```

```
dig cloud.huddeij.de @1.1.1.1

; <<>> DiG 9.18.33-1~deb12u2-Debian <<>> cloud.huddeij.de @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36606
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;cloud.huddeij.de.              IN      A

;; ANSWER SECTION:
cloud.huddeij.de.       86400   IN      A       <new_ip>

;; Query time: 12 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Fri Feb 21 13:35:02 CET 2025
;; MSG SIZE  rcvd: 61

❯ dig cloud.huddeij.de @192.168.0.42

; <<>> DiG 9.18.33-1~deb12u2-Debian <<>> cloud.huddeij.de @192.168.0.42
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40808
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;cloud.huddeij.de.              IN      A

;; ANSWER SECTION:
cloud.huddeij.de.       740     IN      A       <old_ip>

;; Query time: 16 msec
;; SERVER: 192.168.0.42#53(192.168.0.42) (UDP)
;; WHEN: Fri Feb 21 13:35:08 CET 2025
;; MSG SIZE  rcvd: 61
```

I would like to add the removal of dns cache or something like that to the update ips to my provider script, if this is somehow possible

![Image](https://github.com/user-attachments/assets/0c6ceb3a-c07d-4ead-aacc-bf9860bebd34)
