### ISSUE TITLE
Update to piHole v6

### ISSUE THREAD

**Issue by amuessig** [mpgirro/docker-pihole-unbound#276]
Are there plans to update this repository to piHole v6 (including all the docker images)?

**Comment by caferen** [comment]
For anyone looking to switch to v6 now, it's actually pretty trivial to use `unbound` with the official `pihole` image. You can use [`service network_mode`](https://docs.docker.com/reference/compose-file/services/#network_mode) of compose to have an `unbound` image run in the same network namespace as `pihole` and point `pihole` to its own localhost. `unbound.conf` is simply the configuration from the [official pihole docs](https://docs.pi-hole.net/guides/dns/unbound/#configure-unbound). 

Note: we're mounting to `/etc/unbound/unbound.conf` instead of `/etc/unbound/unbound.conf.d/pi-hole.conf` because there's no default configuration file in the Alpine unbound image.

See the [readme](https://docs.pi-hole.net/docker/) and the [migration guide](https://docs.pi-hole.net/docker/upgrading/v5-v6/) before upgrading an existing installation.

Minimal example:

```yaml
services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_dns_upstreams=127.0.0.1#5335
      - FTLCONF_dns_dnssec=true
    volumes:
      - pihole:/etc/pihole
    restart: always
  unbound:
    image: alpinelinux/unbound
    network_mode: service:pihole
    container_name: unbound
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf
    restart: always
 
volumes:
  pihole:

```

**Comment by ryosoftware** [comment]
Hello,
Can you point on how volumes will be mapped?
I assume than etc_pihole-unbound will be mapped in pihole to /etc/pihole, but etc_pihole_dnsmasq-unbound folder will be mapped also to /etc/dnsmasq.d ?
Also, in unbound container the config file (unbound.conf) will be mapped to /etc/unbound/unbound.conf, but any other file needs to be mapped?
Thanks

> For anyone looking to switch to v6 now, it's actually pretty trivial to use `unbound` with the official `pihole` image. You can use [`service network_mode`](https://docs.docker.com/reference/compose-file/services/#network_mode) of compose to have an `unbound` image run in the same network namespace as `pihole` and point `pihole` to its own localhost. `unbound.conf` is simply the configuration from the [official pihole docs](https://docs.pi-hole.net/guides/dns/unbound/#configure-unbound).
> 
> Note: we're mounting to `/etc/unbound/unbound.conf` instead of `/etc/unbound/unbound.conf.d/pi-hole.conf` because there's no default configuration file in the Alpine unbound image.
>

**Comment by caferen** [comment]
> Hello, Can you point on how volumes will be mapped? I assume than etc_pihole-unbound will be mapped in pihole to /etc/pihole, but etc_pihole_dnsmasq-unbound folder will be mapped also to /etc/dnsmasq.d ? Also, in unbound container the config file (unbound.conf) will be mapped to /etc/unbound/unbound.conf, but any other file needs to be mapped? Thanks
> 
> > For anyone looking to switch to v6 now, it's actually pretty trivial to use `unbound` with the official `pihole` image. You can use [`service network_mode`](https://docs.docker.com/reference/compose-file/services/#network_mode) of compose to have an `unbound` image run in the same network namespace as `pihole` and point `pihole` to its own localhost. `unbound.conf` is simply the configuration from the [official pihole docs](https://docs.pi-hole.net/guides/dns/unbound/#configure-unbound).
> > Note: we're mounting to `/etc/unbound/unbound.conf` instead of `/etc/unbound/unbound.conf.d/pi-hole.conf` because there's no default configuration file in the Alpine unbound image.

@kslcsdalsadg That's right. You no longer need the second volume (refer to the readme for instructions). I'd suggest exporting your data from the old instance and start a fresh compose project, then import your data back. This will allow you to preserve your old volumes in case something goes wrong during migration.

**Comment by mashb1t** [comment]
fyi this is my unbound.conf, incl. DoH (Cloudflare):

<details><summary>full unbound.conf</summary>
<p>

```
# Config pulled from https://docs.pi-hole.net/guides/unbound/

server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: yes

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # Suggested by the unbound man page to reduce fragmentation reassembly problems
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    # Be aware that if enabled (requires CAP_NET_ADMIN or privileged), the kernel buffer must have the defined amount of memory, if not, a warning will be raised.
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10

    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

forward-zone:
    name: "."
    forward-tls-upstream: yes

    # Cloudflare
    forward-addr: 1.1.1.1@853
    forward-addr: 1.0.0.1@853
    forward-addr: 2606:4700:4700::1111@853
    forward-addr: 606:4700:4700::1001@853
``` 

</p>
</details> 

<details><summary>alternative forward-zones (e.g. Quad9)</summary>
<p>

```
    ## Cloudflare
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
    forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
    forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

    ## Cloudflare Malware
    # forward-addr: 1.1.1.2@853#security.cloudflare-dns.com
    # forward-addr: 1.0.0.2@853#security.cloudflare-dns.com
    # forward-addr: 2606:4700:4700::1112@853#security.cloudflare-dns.com
    # forward-addr: 2606:4700:4700::1002@853#security.cloudflare-dns.com

    ## Cloudflare Malware and Adult Content
    # forward-addr: 1.1.1.3@853#family.cloudflare-dns.com
    # forward-addr: 1.0.0.3@853#family.cloudflare-dns.com
    # forward-addr: 2606:4700:4700::1113@853#family.cloudflare-dns.com
    # forward-addr: 2606:4700:4700::1003@853#family.cloudflare-dns.com

    ## CleanBrowsing Security Filter
    # forward-addr: 185.228.168.9@853#security-filter-dns.cleanbrowsing.org
    # forward-addr: 185.228.169.9@853#security-filter-dns.cleanbrowsing.org
    # forward-addr: 2a0d:2a00:1::2@853#security-filter-dns.cleanbrowsing.org
    # forward-addr: 2a0d:2a00:2::2@853#security-filter-dns.cleanbrowsing.org

    ## CleanBrowsing Adult Filter
    # forward-addr: 185.228.168.10@853#adult-filter-dns.cleanbrowsing.org
    # forward-addr: 185.228.169.11@853#adult-filter-dns.cleanbrowsing.org
    # forward-addr: 2a0d:2a00:1::1@853#adult-filter-dns.cleanbrowsing.org
    # forward-addr: 2a0d:2a00:2::1@853#adult-filter-dns.cleanbrowsing.org

    ## CleanBrowsing Family Filter
    # forward-addr: 185.228.168.168@853#family-filter-dns.cleanbrowsing.org
    # forward-addr: 185.228.169.168@853#family-filter-dns.cleanbrowsing.org
    # forward-addr: 2a0d:2a00:1::@853#family-filter-dns.cleanbrowsing.org
    # forward-addr: 2a0d:2a00:2::@853#family-filter-dns.cleanbrowsing.org

    ## Quad9
    # forward-addr: 9.9.9.9@853#dns.quad9.net
    # forward-addr: 149.112.112.112@853#dns.quad9.net
    # forward-addr: 2620:fe::fe@853#dns.quad9.net
    # forward-addr: 2620:fe::9@853#dns.quad9.net

    ## getdnsapi.net
    # forward-addr: 185.49.141.37@853#getdnsapi.net
    # forward-addr: 2a04:b900:0:100::37@853#getdnsapi.net
``` 

</p>
</details> 

You can check https://1.1.1.1/help to see if DoT has correctly been enabled.

Keep in mind that the capability "NET_ADMIN" should be added to unbound in the docker-compose file to increase the buffer on traffic spikes.
