### ISSUE TITLE
Error: DNS resolution is currently unavailable

### ISSUE THREAD

**Issue by VeloAddict** [mpgirro/docker-pihole-unbound#289]
```
version: "3.9"
services:
  pihole:
    image: mpgirro/pihole-unbound:latest
    container_name: pihole
    environment:
      - TZ=Europe/Bucharest
      - PIHOLE_UID=1000
      - PIHOLE_GID=100
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_misc_etc_dnsmasq_d=true
      - FTLCONF_dns_domain=${DOMAIN_NAME}
      - FTLCONF_dns_upstreams=127.0.0.1#5335;127.0.0.1#5335
      - FTLCONF_dhcp_active=${DHCP_ACTIVE}
      - FTLCONF_dhcp_start=${DHCP_START}
      - FTLCONF_dhcp_end=${DHCP_END}
      - FTLCONF_dhcp_router=${DHCP_ROUTER}
      - FTLCONF_dhcp_rapidCommit=true
      - FTLCONF_webserver_api_password=${WEBPASSWORD}
    volumes:
      - /path/to/pihole/data:/etc/pihole/
      - /path/to/pihole/logs:/var/log/pihole
    ports:
      - "${IPV4}:53:53/tcp"
      - "${IPV4}:53:53/udp"
      - "5335:5335/tcp"
      - "5443:443/tcp"
    depends_on:
      - dhcphelper
    dns:
      - 127.0.0.1
    networks:
      virgo:
        ipv4_address: 172.30.0.4
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  dhcphelper:
    container_name: dhcphelper
    image: homeall/dhcphelper:latest
    network_mode: host
    environment:
      IP: 172.30.0.4
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  virgo:
    external: true
```

`/path/to/pihole` does not exist, fresh volumes, clean stack deployment, on first start:
```
  [i] Starting Unbound
  [i] Unbound started successfully with PID 9
  [i] Setting up user & group for the pihole user
  [i] ID for user pihole is already 1000, no need to change
  [i] Changing ID for group: pihole (1000 => 100)
  [i] Starting FTL configuration
  [i] Assigning password defined by Environment Variable
  [i] Starting crond for scheduled scripts. Randomizing times for gravity and update checker
  [i] Ensuring logrotate script exists in /etc/pihole
  [i] Gravity migration checks
  [i] No adlist file found, creating one with a default blocklist
  [i] /etc/pihole/gravity.db does not exist (Likely due to a fresh volume). This is a required file for Pi-hole to operate.
  [i] Gravity will now be run to create the database
  [i] Migrating the list's cache directory to new location...
  [✗] Migrating the list's cache directory to new location
  [i] Creating new gravity database
  [i] Migrating content of /etc/pihole/adlists.list into new database
  [✗] DNS resolution is currently unavailable
```

After restarting the pihole container everything works fine.

With clean pihole 5 deployment never had this issue.
Upgrading from 5 to 6 also works.
Only problem is deploying clean with version 6.

Any ideas why this could be?
